### ISSUE TITLE
Upgrade to Laravel 6

### ISSUE THREAD

**Issue by HadrienX** [krossroad/laravel-unionpaginator#16] opened 2019-09-23 20:50 UTC
Your project is not compatible with Laravel 6.
If we're trying to upgrade to Laravel 6 and having your project in our dependency, we get this message : 

> krossroad/laravel-union-paginator v5.5.4 requires illuminate/pagination ^5.5

**Comment by krossroad** [comment] 2019-09-24 04:36
@HadrienX this issue is duplicate of #15

**Closed** 2019-09-25 06:45 UTC
